cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_springboot_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: Alex#1985
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # properties:
      # hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
spring-doc:
  pathsToMatch:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true